#!/bin/bash

# Use for loop to iterate over files in the current directory
for file in *
do
    # Check if the file is not a hidden file
    if [[ ! $file == .* ]]; then
        # Extract part of the name after the first dash
        name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
        
        # Display the modified name
        echo "$name_after_dash"
    fi
done
